stages:
  prepare:
    cmd: python src/data.py
    deps:
      - src/data.py
      - configs/config.yaml
    outs:
      - data/digits_subset.pkl
  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - src/model.py
      - src/utils.py
      - data/digits_subset.pkl
      - configs/config.yaml
    outs:
      - models/digits_mlp.pth